# Generated by Django 3.1.4 on 2021-02-15 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210211_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.post'),
        ),
    ]
